version: '3.1'
networks: 
  wpnet:
services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./wp-config.php:/config/wp-config.php
      - ./html/:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    links:
    - mysql
    networks: 
      - wpnet
  mysql:
    container_name: mysql
    hostname: localhost
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks: 
      - wpnet